POST http://localhost:3000/api/getResponse
{
    "model": "llama-3-1-70b",
    "pipeKey": "0x0f9da2be6d3e7226a312c503bdf9ca9c12edeff288fe3412c1d9cfc6e09a2afa",
    "address": "0x945319c475F1e20048E390D99e80972143bb8552",
    "inputJson": {
        "query": "Deepseek",
        "question": "what is the latest news about deepseek?"
    }
}

HTTP/1.1 200  - OK
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch
content-type: application/json
date: Sat, 05 Apr 2025 16:37:11 GMT
connection: close
transfer-encoding: chunked