POST http://localhost:3000/api/getResponse
{
    "model": "llama-3-1-70b",
    "pipeKey": "0xd00508004cec837a3c540eb449b203551c304a13254487d132e385e034f77e18",
    "address": "0xcaA2475b077926173043A91dd47e57f8F50a2926",
    "inputJson": {
        "query": "Deepseek",
        "question": "what is the latest news about deepseek?"
    }
}

HTTP/1.1 200  - OK
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch
content-type: application/json
date: Sun, 06 Apr 2025 12:46:34 GMT
connection: close
transfer-encoding: chunked