POST http://localhost:3000/api/getResponse
{
    "model": "meta-llama/Meta-Llama-3-70B-Instruct-Turbo",
    "pipeKey": "0x4b81ba199c140c65de3741fcf618bb80987a6588edcf35d3058c704a3f41b01b",
    "address": "0x2F8110491E604ADCBdF50F5f100CDd46FFbeb344",
    "inputJson": {
        "query": "Deepseek",
        "question": "what is the latest news about deepseek?"
    }
}