compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/AltNode.ts --network sonicTestnet

verify:
	npx hardhat verify --network sonicTestnet 0x64801c4e53b942Ff5d5eef0b77f4FA5024b03D56

deploy-token:
	npx hardhat run ignition/modules/token.ts --network sonicTestnet

verify-token:
	npx hardhat verify --network sonicTestnet 0x6562601Dee56446db027fAC457a5c85a5856c375
